language: ruby
dist: bionic
before_install:
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y texlive-font-utils
  - sudo apt-get install -y ghostscript
script: make all
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master
env:
  global:
    secure: Tot/AgiLHELk8TwHn6LjfOK4m0gHApAdgbQQ9IkNBO6oKMdskAdpcZz6709YgQv+VMRF3sYfV7wqCDkNZlAcXF86ram+zPx/dP+Nx5MjPVT15jK0My768ShVnTJtj2HLev1/RoTUtP+IOvCrsRP2/NKJCb2L2TmvvYaHtD0aNrZQGgXTm4t4/xYVw2dL9ub1l1/PKJri8MUniE7P4+H+n9FjzdwI0xmlcBFP4hFiTP7gA9srWEteGCc2rLZGwPRWVjxSlhymGOnfako3icrRnxr2ttEOyvXqJ1FemxI3mwU/5X5b8FNS8hIb38oVuJ+XBDKAnOytzERLXmIVD9Iagudhl3ZDXsrZWYEtVE2O3rcZQJfznN3mp2kK4ScnMewbosAE9i4caFzQ5iLg1UeSGcAzEJN6fA335yqD0YQIntvVBz+YVHHAyTMonyRPKuxonuZs7VYYIh7j6ppHRPrA+yp3DuwPTdbGM7qnYh1ruqNuNtV3PlMntbNkWg8G4yPvONx3vJ45pvqUKFLqdTtS1nzBKoBGi6rPw6U27Y+LcILTkiCEhc2V+13/5BEahLj2Hac+G/LXtsjs7NKP/vQErcvj17ynzzqNwbXGXCe9Jvofla02KN1KzzDG+DIX+YkiiYI+jeWn3ZgdMxe3czLU6DJR/OdIaeyjp3mxHo2ewuk=
